### ISSUE TITLE
Obtain supported animations from ROS node.

### ISSUE THREAD

**Issue by linas** [hansonrobotics/ros_motors_webui#2]
Currently, the list of supported animations is hard-coded in index.html. To really work properly, these should be obtained from the rig ros node, as different heads will have different animations associated with them.

Similarly, the list of motors will be head-dependent, as well.  I guess the short-term hack is to pull them out of a yaml file, but that will then make this GUI work for only one robot, and there won't be any easy way of usig it on a different robot without hacking around.

**Comment by vytasrgl** [comment]
Already solved
